CREATE ROLE "krs-backend" LOGIN;
CREATE DATABASE "krs-backend" OWNER "krs-backend";
\c "krs-backend";
SET ROLE "krs-backend";
CREATE TABLE IF NOT EXISTS "v1.places" (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "description" text,
    "name" text,
    phone text,
    website text
);
INSERT INTO "v1.places" ("name", "description", "website") VALUES
    ('Place One', 'Brewery', 'http://www.brewery.com'),
    ('Place Two', 'Pizza', 'http://www.pizza.com');
