CREATE ROLE "krs-backend" LOGIN PASSWORD 'krs-backend';
CREATE DATABASE "krs-backend" OWNER "krs-backend";
\c "krs-backend";
SET ROLE "krs-backend";
CREATE SCHEMA IF NOT EXISTS v1 AUTHORIZATION "krs-backend";
CREATE TABLE IF NOT EXISTS v1.places (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "description" text,
    "name" text,
    phone text,
    website text
);

INSERT INTO v1.places ("name", "description", "website") VALUES
    ('Postdoc Brewing Redmond', 'Brewery, food trucks', 'https://www.postdocbrewing.com/'),
    ('Valley House Brewing Company', 'Brewery, In-house Kitchen', 'https://www.valleyhousebrewing.com');
