CREATE ROLE "krs-backend" LOGIN PASSWORD 'krs-backend';
CREATE DATABASE "krs-backend" OWNER "krs-backend";

\c "krs-backend";
SET ROLE "krs-backend";

CREATE SCHEMA IF NOT EXISTS v1 AUTHORIZATION "krs-backend";

CREATE TABLE IF NOT EXISTS v1.places (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "description" text,
    "name" text
);

-- A place may have 0-M phone numbers.
CREATE TABLE IF NOT EXISTS v1.place_phone (
    place_id integer REFERENCES v1.places(id),
    phone text
);

-- A place may also have 0-M websites. For example, a place with several
-- locations having location-specific websites.
CREATE TABLE IF NOT EXISTS v1.place_website (
    place_id integer REFERENCES v1.places(id),
    website text
);

INSERT INTO v1.places ("id", "name", "description") VALUES
    (1, 'Postdoc Brewing Redmond', 'Brewery, food trucks'),
    (2, 'Valley House Brewing Company', 'Brewery, In-house Kitchen');

INSERT INTO v1.place_website ("place_id", "website") VALUES
    (1, 'https://www.postdocbrewing.com/'),
    (2, 'https://www.valleyhousebrewing.com')
