//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Address defines model for Address.
type Address struct {
	City       string             `json:"city"`
	Country    string             `json:"country"`
	Id         openapi_types.UUID `json:"id"`
	PostalCode string             `json:"postalCode"`
	Region     *string            `json:"region"`
	Street     string             `json:"street"`
	Unit       *string            `json:"unit"`
}

// AddressCreate defines model for AddressCreate.
type AddressCreate struct {
	City       string  `json:"city"`
	Country    string  `json:"country"`
	PostalCode string  `json:"postalCode"`
	Region     *string `json:"region,omitempty"`
	Street     string  `json:"street"`
	Unit       *string `json:"unit,omitempty"`
}

// AddressUpdate defines model for AddressUpdate.
type AddressUpdate struct {
	City       string              `json:"city"`
	Country    string              `json:"country"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	PostalCode string              `json:"postalCode"`
	Region     *string             `json:"region,omitempty"`
	Street     string              `json:"street"`
	Unit       *string             `json:"unit,omitempty"`
}

// Restaurant defines model for Restaurant.
type Restaurant struct {
	// AddressId Reference to an Address id
	AddressId   openapi_types.UUID `json:"addressId"`
	Description *string            `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Phone       *string            `json:"phone"`
	Website     *string            `json:"website"`
}

// RestaurantCreate defines model for RestaurantCreate.
type RestaurantCreate struct {
	AddressId   openapi_types.UUID `json:"addressId"`
	Description *string            `json:"description,omitempty"`
	Name        string             `json:"name"`
	Phone       *string            `json:"phone,omitempty"`
	Website     *string            `json:"website,omitempty"`
}

// RestaurantUpdate defines model for RestaurantUpdate.
type RestaurantUpdate struct {
	AddressId   openapi_types.UUID  `json:"addressId"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        string              `json:"name"`
	Phone       *string             `json:"phone,omitempty"`
	Website     *string             `json:"website,omitempty"`
}

// ListAddressesParams defines parameters for ListAddresses.
type ListAddressesParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListRestaurantsParams defines parameters for ListRestaurants.
type ListRestaurantsParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAddressJSONRequestBody defines body for CreateAddress for application/json ContentType.
type CreateAddressJSONRequestBody = AddressCreate

// UpdateAddressJSONRequestBody defines body for UpdateAddress for application/json ContentType.
type UpdateAddressJSONRequestBody = AddressUpdate

// CreateRestaurantJSONRequestBody defines body for CreateRestaurant for application/json ContentType.
type CreateRestaurantJSONRequestBody = RestaurantCreate

// UpdateRestaurantJSONRequestBody defines body for UpdateRestaurant for application/json ContentType.
type UpdateRestaurantJSONRequestBody = RestaurantUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List addresses
	// (GET /addresses)
	ListAddresses(w http.ResponseWriter, r *http.Request, params ListAddressesParams)
	// Create an address
	// (POST /addresses)
	CreateAddress(w http.ResponseWriter, r *http.Request)
	// Delete an address
	// (DELETE /addresses/{id})
	DeleteAddress(w http.ResponseWriter, r *http.Request, id string)
	// Get an address by id
	// (GET /addresses/{id})
	GetAddress(w http.ResponseWriter, r *http.Request, id string)
	// Update an address
	// (PUT /addresses/{id})
	UpdateAddress(w http.ResponseWriter, r *http.Request, id string)
	// List restaurants
	// (GET /restaurants)
	ListRestaurants(w http.ResponseWriter, r *http.Request, params ListRestaurantsParams)
	// Create a restaurant
	// (POST /restaurants)
	CreateRestaurant(w http.ResponseWriter, r *http.Request)
	// Delete a restaurant
	// (DELETE /restaurants/{id})
	DeleteRestaurant(w http.ResponseWriter, r *http.Request, id string)
	// Get a restaurant by id
	// (GET /restaurants/{id})
	GetRestaurant(w http.ResponseWriter, r *http.Request, id string)
	// Update a restaurant
	// (PUT /restaurants/{id})
	UpdateRestaurant(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAddresses operation middleware
func (siw *ServerInterfaceWrapper) ListAddresses(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAddressesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAddresses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAddress operation middleware
func (siw *ServerInterfaceWrapper) CreateAddress(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAddress(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAddress operation middleware
func (siw *ServerInterfaceWrapper) DeleteAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAddress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAddress operation middleware
func (siw *ServerInterfaceWrapper) GetAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAddress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAddress operation middleware
func (siw *ServerInterfaceWrapper) UpdateAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAddress(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRestaurants operation middleware
func (siw *ServerInterfaceWrapper) ListRestaurants(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRestaurantsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRestaurants(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRestaurant operation middleware
func (siw *ServerInterfaceWrapper) CreateRestaurant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRestaurant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRestaurant operation middleware
func (siw *ServerInterfaceWrapper) DeleteRestaurant(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRestaurant(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRestaurant operation middleware
func (siw *ServerInterfaceWrapper) GetRestaurant(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRestaurant(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRestaurant operation middleware
func (siw *ServerInterfaceWrapper) UpdateRestaurant(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRestaurant(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/addresses", wrapper.ListAddresses)
	m.HandleFunc("POST "+options.BaseURL+"/addresses", wrapper.CreateAddress)
	m.HandleFunc("DELETE "+options.BaseURL+"/addresses/{id}", wrapper.DeleteAddress)
	m.HandleFunc("GET "+options.BaseURL+"/addresses/{id}", wrapper.GetAddress)
	m.HandleFunc("PUT "+options.BaseURL+"/addresses/{id}", wrapper.UpdateAddress)
	m.HandleFunc("GET "+options.BaseURL+"/restaurants", wrapper.ListRestaurants)
	m.HandleFunc("POST "+options.BaseURL+"/restaurants", wrapper.CreateRestaurant)
	m.HandleFunc("DELETE "+options.BaseURL+"/restaurants/{id}", wrapper.DeleteRestaurant)
	m.HandleFunc("GET "+options.BaseURL+"/restaurants/{id}", wrapper.GetRestaurant)
	m.HandleFunc("PUT "+options.BaseURL+"/restaurants/{id}", wrapper.UpdateRestaurant)

	return m
}

type ListAddressesRequestObject struct {
	Params ListAddressesParams
}

type ListAddressesResponseObject interface {
	VisitListAddressesResponse(w http.ResponseWriter) error
}

type ListAddresses200JSONResponse struct {
	Items *[]Address `json:"items,omitempty"`
	Total *int       `json:"total,omitempty"`
}

func (response ListAddresses200JSONResponse) VisitListAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateAddressRequestObject struct {
	Body *CreateAddressJSONRequestBody
}

type CreateAddressResponseObject interface {
	VisitCreateAddressResponse(w http.ResponseWriter) error
}

type CreateAddress201JSONResponse Address

func (response CreateAddress201JSONResponse) VisitCreateAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAddressRequestObject struct {
	Id string `json:"id"`
}

type DeleteAddressResponseObject interface {
	VisitDeleteAddressResponse(w http.ResponseWriter) error
}

type DeleteAddress204Response struct {
}

func (response DeleteAddress204Response) VisitDeleteAddressResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAddress404Response struct {
}

func (response DeleteAddress404Response) VisitDeleteAddressResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetAddressRequestObject struct {
	Id string `json:"id"`
}

type GetAddressResponseObject interface {
	VisitGetAddressResponse(w http.ResponseWriter) error
}

type GetAddress200JSONResponse Address

func (response GetAddress200JSONResponse) VisitGetAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAddress404Response struct {
}

func (response GetAddress404Response) VisitGetAddressResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateAddressRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateAddressJSONRequestBody
}

type UpdateAddressResponseObject interface {
	VisitUpdateAddressResponse(w http.ResponseWriter) error
}

type UpdateAddress200JSONResponse Address

func (response UpdateAddress200JSONResponse) VisitUpdateAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAddress404Response struct {
}

func (response UpdateAddress404Response) VisitUpdateAddressResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListRestaurantsRequestObject struct {
	Params ListRestaurantsParams
}

type ListRestaurantsResponseObject interface {
	VisitListRestaurantsResponse(w http.ResponseWriter) error
}

type ListRestaurants200JSONResponse struct {
	Items *[]Restaurant `json:"items,omitempty"`
	Total *int          `json:"total,omitempty"`
}

func (response ListRestaurants200JSONResponse) VisitListRestaurantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateRestaurantRequestObject struct {
	Body *CreateRestaurantJSONRequestBody
}

type CreateRestaurantResponseObject interface {
	VisitCreateRestaurantResponse(w http.ResponseWriter) error
}

type CreateRestaurant201JSONResponse Restaurant

func (response CreateRestaurant201JSONResponse) VisitCreateRestaurantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteRestaurantRequestObject struct {
	Id string `json:"id"`
}

type DeleteRestaurantResponseObject interface {
	VisitDeleteRestaurantResponse(w http.ResponseWriter) error
}

type DeleteRestaurant204Response struct {
}

func (response DeleteRestaurant204Response) VisitDeleteRestaurantResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteRestaurant404Response struct {
}

func (response DeleteRestaurant404Response) VisitDeleteRestaurantResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetRestaurantRequestObject struct {
	Id string `json:"id"`
}

type GetRestaurantResponseObject interface {
	VisitGetRestaurantResponse(w http.ResponseWriter) error
}

type GetRestaurant200JSONResponse Restaurant

func (response GetRestaurant200JSONResponse) VisitGetRestaurantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRestaurant404Response struct {
}

func (response GetRestaurant404Response) VisitGetRestaurantResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateRestaurantRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateRestaurantJSONRequestBody
}

type UpdateRestaurantResponseObject interface {
	VisitUpdateRestaurantResponse(w http.ResponseWriter) error
}

type UpdateRestaurant200JSONResponse Restaurant

func (response UpdateRestaurant200JSONResponse) VisitUpdateRestaurantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRestaurant404Response struct {
}

func (response UpdateRestaurant404Response) VisitUpdateRestaurantResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List addresses
	// (GET /addresses)
	ListAddresses(ctx context.Context, request ListAddressesRequestObject) (ListAddressesResponseObject, error)
	// Create an address
	// (POST /addresses)
	CreateAddress(ctx context.Context, request CreateAddressRequestObject) (CreateAddressResponseObject, error)
	// Delete an address
	// (DELETE /addresses/{id})
	DeleteAddress(ctx context.Context, request DeleteAddressRequestObject) (DeleteAddressResponseObject, error)
	// Get an address by id
	// (GET /addresses/{id})
	GetAddress(ctx context.Context, request GetAddressRequestObject) (GetAddressResponseObject, error)
	// Update an address
	// (PUT /addresses/{id})
	UpdateAddress(ctx context.Context, request UpdateAddressRequestObject) (UpdateAddressResponseObject, error)
	// List restaurants
	// (GET /restaurants)
	ListRestaurants(ctx context.Context, request ListRestaurantsRequestObject) (ListRestaurantsResponseObject, error)
	// Create a restaurant
	// (POST /restaurants)
	CreateRestaurant(ctx context.Context, request CreateRestaurantRequestObject) (CreateRestaurantResponseObject, error)
	// Delete a restaurant
	// (DELETE /restaurants/{id})
	DeleteRestaurant(ctx context.Context, request DeleteRestaurantRequestObject) (DeleteRestaurantResponseObject, error)
	// Get a restaurant by id
	// (GET /restaurants/{id})
	GetRestaurant(ctx context.Context, request GetRestaurantRequestObject) (GetRestaurantResponseObject, error)
	// Update a restaurant
	// (PUT /restaurants/{id})
	UpdateRestaurant(ctx context.Context, request UpdateRestaurantRequestObject) (UpdateRestaurantResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAddresses operation middleware
func (sh *strictHandler) ListAddresses(w http.ResponseWriter, r *http.Request, params ListAddressesParams) {
	var request ListAddressesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAddresses(ctx, request.(ListAddressesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAddresses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAddressesResponseObject); ok {
		if err := validResponse.VisitListAddressesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAddress operation middleware
func (sh *strictHandler) CreateAddress(w http.ResponseWriter, r *http.Request) {
	var request CreateAddressRequestObject

	var body CreateAddressJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAddress(ctx, request.(CreateAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAddressResponseObject); ok {
		if err := validResponse.VisitCreateAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAddress operation middleware
func (sh *strictHandler) DeleteAddress(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteAddressRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAddress(ctx, request.(DeleteAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAddressResponseObject); ok {
		if err := validResponse.VisitDeleteAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAddress operation middleware
func (sh *strictHandler) GetAddress(w http.ResponseWriter, r *http.Request, id string) {
	var request GetAddressRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAddress(ctx, request.(GetAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAddressResponseObject); ok {
		if err := validResponse.VisitGetAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAddress operation middleware
func (sh *strictHandler) UpdateAddress(w http.ResponseWriter, r *http.Request, id string) {
	var request UpdateAddressRequestObject

	request.Id = id

	var body UpdateAddressJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAddress(ctx, request.(UpdateAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAddressResponseObject); ok {
		if err := validResponse.VisitUpdateAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRestaurants operation middleware
func (sh *strictHandler) ListRestaurants(w http.ResponseWriter, r *http.Request, params ListRestaurantsParams) {
	var request ListRestaurantsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRestaurants(ctx, request.(ListRestaurantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRestaurants")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRestaurantsResponseObject); ok {
		if err := validResponse.VisitListRestaurantsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRestaurant operation middleware
func (sh *strictHandler) CreateRestaurant(w http.ResponseWriter, r *http.Request) {
	var request CreateRestaurantRequestObject

	var body CreateRestaurantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRestaurant(ctx, request.(CreateRestaurantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRestaurant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRestaurantResponseObject); ok {
		if err := validResponse.VisitCreateRestaurantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteRestaurant operation middleware
func (sh *strictHandler) DeleteRestaurant(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteRestaurantRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRestaurant(ctx, request.(DeleteRestaurantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRestaurant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteRestaurantResponseObject); ok {
		if err := validResponse.VisitDeleteRestaurantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRestaurant operation middleware
func (sh *strictHandler) GetRestaurant(w http.ResponseWriter, r *http.Request, id string) {
	var request GetRestaurantRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRestaurant(ctx, request.(GetRestaurantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRestaurant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRestaurantResponseObject); ok {
		if err := validResponse.VisitGetRestaurantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRestaurant operation middleware
func (sh *strictHandler) UpdateRestaurant(w http.ResponseWriter, r *http.Request, id string) {
	var request UpdateRestaurantRequestObject

	request.Id = id

	var body UpdateRestaurantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRestaurant(ctx, request.(UpdateRestaurantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRestaurant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateRestaurantResponseObject); ok {
		if err := validResponse.VisitUpdateRestaurantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
